// frontend/vuejs/src/components/TodoList.vue
<template>
  <table>
    <thead>
    <tr>
      <th rowspan="2">My todos ({{viewModel.ongoingCount}}} ongoing
        /{{viewModel.doneCount}}} done/ {{viewModel.clickCount}}} clicks)
        <button @click="presenter.addEmptyTodo()">Add</button>
      </th>
    </tr>
    </thead>
    <tbody>
    <tr v-for="(todo, i) in viewModel.todos" :key="i">
      <td @click="presenter.incrementClickCount()">
        <label :for="'done' + todo.id">{{todo.title}}</label>
      </td>
      <td>
        <input type="checkbox" 
               value="1" 
               :id="'done' + todo.id" 
               :checked="todo.done"
               @change="presenter.toggleDone(i)"/>
      </td>
    </tr>
    </tbody>
  </table>
</template>

<script>
import {TodoListPresenter} from '@frontend/app/Todo/TodoListPresenter';
import {getTodos} from '@frontend/app/Todo/todo.service';

export default {
  name: 'TodoList',
  setup() {
    return { presenter: new TodoListPresenter({getTodos}) }
  },
  data() {
    return {
      viewModel: this.presenter.viewModel
    }
  },
  created() {
    this.presenter.onViewModelChange(vm => this.viewModel = vm);
    this.presenter.loadTodos();
  }
}
</script>

// frontend/react/src/Todo/TodoList.js
import {useEffect, useMemo, useState} from 'react';
import {getTodos} from '@/frontend/app/Todo/todo.service';
import {TodoListPresenter} from '@/frontend/app/Todo/TodoListPresenter';


const TodoList = ({presenter, viewModel}) => {
  useEffect(() => {
    presenter.loadTodos();
  }, [presenter]);

  return <>
    <table>
      <thead>
      <tr>
        <th rowSpan={2} align="left">My todos ({viewModel.ongoingCount} ongoing
          /{viewModel.doneCount} done/ {viewModel.clickCount} clicks)
          <button onClick={() => presenter.addEmptyTodo()}>Add</button>
        </th>
      </tr>
      </thead>
      <tbody>
      {viewModel.todos.map((todo, index) => (
        <tr key={todo.id}>
          <td onClick={() => presenter.incrementClickCount()}><label htmlFor={`done-${todo.id}`}>{todo.title}</label>
          </td>
          <td><input type="checkbox" value="1" id={`done-${todo.id}`} checked={todo.done}
                     onChange={() => presenter.toggleDone(index)}/></td>
        </tr>
      ))}
      </tbody>
    </table>
  </>;
};

export const withMVP = (Wrapped) =>
  function WithTodoPresenter() {
    const [viewModel, setViewModel] = useState();

    const presenter = useMemo(() => {
      const presenter = new TodoListPresenter({getTodos});
      presenter.onViewModelChange(setViewModel);
      return presenter;
    }, []);

    return <Wrapped presenter={presenter} viewModel={viewModel || presenter.immutableViewModel()}/>;
  };


export default withMVP(TodoList);
